# Generated by Django 6.0.6 on 2026-08-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SAFE', 'Safe'), ('SUSPICIOUS', 'Suspicious'), ('MINING', 'Mining')], max_length=20)),
                ('result', models.TextField()),
                ('detected_processes', models.JSONField(default=list)),
                ('risk_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prevention_unlocked', models.BooleanField(default=False)),
            ],
        ),
    ]
