# Generated by Django 6.0.6 on 2026-08-16 19:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_logs_collected', models.IntegerField(default=0)),
                ('total_mining_detections', models.IntegerField(default=0)),
                ('total_suspicious_connections', models.IntegerField(default=0)),
                ('total_miner_processes', models.IntegerField(default=0)),
                ('last_detection', models.DateTimeField(blank=True, null=True)),
                ('last_safe_scan', models.DateTimeField(blank=True, null=True)),
                ('detections_past_7_days', models.IntegerField(default=0)),
                ('detections_past_30_days', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log_analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('fqdn', models.CharField(max_length=255, verbose_name='FQDN (Domain)')),
                ('ip_addresses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=45), blank=True, default=list)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_recv', models.BigIntegerField(default=0)),
                ('packets_sent', models.BigIntegerField(default=0)),
                ('packets_recv', models.BigIntegerField(default=0)),
                ('mining_detected', models.BooleanField(default=False)),
                ('detection_status', models.CharField(choices=[('safe', 'Safe - No Mining Detected'), ('suspicious', 'Suspicious - Mining Activity Detected'), ('pending_review', 'Pending Review')], default='safe', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ESTABLISHED', 'Established'), ('LISTEN', 'Listening'), ('TIME_WAIT', 'Time Wait'), ('CLOSE_WAIT', 'Close Wait'), ('SYN_SENT', 'SYN Sent'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('local_ip', models.GenericIPAddressField()),
                ('local_port', models.IntegerField()),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('remote_port', models.IntegerField(blank=True, null=True)),
                ('process_id', models.IntegerField(blank=True, null=True)),
                ('is_mining_port', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_connections', to='logs_monitering.systemlog')),
            ],
            options={
                'verbose_name_plural': 'Suspicious Connections',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='MinerProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.IntegerField()),
                ('process_name', models.CharField(max_length=255)),
                ('command_line', models.TextField()),
                ('confidence_score', models.FloatField(default=0.9, help_text='Confidence level (0-1) that this is a miner process')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miner_processes', to='logs_monitering.systemlog')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['-created_at'], name='logs_monite_created_b466cc_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['mining_detected'], name='logs_monite_mining__417195_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['user', '-created_at'], name='logs_monite_user_id_b393cc_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousconnection',
            index=models.Index(fields=['log', '-detected_at'], name='logs_monite_log_id_69db6a_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousconnection',
            index=models.Index(fields=['is_mining_port'], name='logs_monite_is_mini_942de9_idx'),
        ),
        migrations.AddIndex(
            model_name='minerprocess',
            index=models.Index(fields=['log', '-detected_at'], name='logs_monite_log_id_191c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='minerprocess',
            index=models.Index(fields=['process_name'], name='logs_monite_process_614e99_idx'),
        ),
    ]
