# Generated by Django 6.0.6 on 2026-08-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs_monitering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='application_event_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='detection_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='network_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='process_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='security_event_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='system_event_log',
            field=models.TextField(blank=True, default=''),
        ),
    ]
